package jpja.webapp.controllers;

import org.springframework.boot.web.servlet.error.ErrorController;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.ui.Model;

import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.RequestDispatcher;

/**
 * Custom error controller to handle errors generated by the application.
 * This controller displays an error page when an error occurs.
 * 
 * @author James Prial
 */
@Controller
public class CustomErrorController implements ErrorController {

    /**
     * Handles error requests and prepares the error model for display.
     *
     * @param request The HTTP servlet request containing error information.
     * @param model The model used to pass attributes to the view.
     * @return The name of the error view to be rendered.
     */
    @RequestMapping("/error")
    public String handleError(HttpServletRequest request, Model model) {
        Object status = request.getAttribute(RequestDispatcher.ERROR_STATUS_CODE);
        Object errorMessage = request.getAttribute(RequestDispatcher.ERROR_MESSAGE);

        String errorMsg = errorMessage != null ? errorMessage.toString() : "Unknown error occurred";

        if (status != null) {
            int statusCode = Integer.parseInt(status.toString());
            model.addAttribute("status", statusCode);
        } else {
            model.addAttribute("status", "Unknown");
        }

        model.addAttribute("error", "An error occurred!");
        model.addAttribute("message", errorMsg);

        return "error";
    }
}
